### ISSUE TITLE
Create two diffrent endpoints for login/register and the logic behind them

### ISSUE THREAD

**Issue by Jonathandah** [Jonathandah/silver-doodle-chess#7]
One need to handle the login and the other one the registration. Back-End will get name and password. 

Decide minimum length on password and name!

Name minimum 4 character
Password minimum length 6 characters
ex: {username: "jonathan", password: "Tyson2434" }

**Comment by ProGloD** [comment]
Possible endpoints for register and login

POST: `/user/register`
input:
`{username: string, password: string}`
username min length 4 is required
password min length 6 is required
output: 
`statusCode: 201` if created
`statusCode: 400` if username or password are incorrect

POST: `/user/login`
input:
`{username: string, password: string}`
output:
`{username: string}` with `statusCode: 200` if username and password are validated
`statusCode: 400` if username or password are incorrect
